import play as p
from board import TicTacToe

test = TicTacToe()
test.move(0,0)
test.next_player()
test.move(1,1)
test.next_player()
test.move(2,2)
test.next_player()
test.move(1,0)
test.next_player()
test.move(1,2)
test.next_player()
test.move(0,2)
test.next_player()
test.move(2,0)
test.next_player()
test.move(2,1)
test.next_player()
test.move(0,1)
check, reward = test.check_winner_reward()
test.print_board()
print(check, reward)
